### ISSUE TITLE
Compile for Windows

### ISSUE THREAD

**Issue by midwan** [unwind/gimpilbm#1]
It would be great if we could compile this for the Windows version of GIMP also!
Unfortunately I haven't been able to do so until now, even when using a cross compiler under Linux.

**Comment by midwan** [comment]
I've actually forked this and created a Windows build. I'd like to clean it up a bit before I issue a pull request. ;-)

**Comment by unwind** [comment]
Great! I don't have access to a Windows machine for personal projects, so I'll certainly need help. Thanks for your interest!

**Comment by midwan** [comment]
[Makefile-win32.txt](https://github.com/unwind/gimpilbm/files/389497/Makefile-win32.txt)

Great news, with the latest changes you made, I can compile the Windows version under MSYS2 with almost no modifications. I only added a slightly different Makefile for Windows, so that the plugin filename is *.exe instead of *.so as it should be.

I noticed that there are a lot of warnings about using deprecated functions though, is that something you're aware of? I got all the parts from Git directly, so perhaps that has something to do with it, but shouldn't we be using the newer function calls anyway?

These warnings also popped-up in GIMP as requesters when using the plugin to Load / Save images, so they're not just compiler warnings which we can ignore...

I'm attaching a log with the warnings I got when running "make" for your reference.
[gimpilbm-warnings.txt](https://github.com/unwind/gimpilbm/files/389451/gimpilbm-warnings.txt)

Also, I'm attaching a screenshot of one of the warnings in GIMP, to give you an idea...
![gimp message](https://cloud.githubusercontent.com/assets/3877365/17230930/55d75dbe-551f-11e6-8e6f-592032a54293.png)

EDIT: I just checked GIMP 2.8 as well, the warnings do not appear there, so it seems these are deprecated in 2.9 onwards.

EDIT2: I'm also attaching the Windows Makefile I prepared. Not sure if it's worth doing a complete pull request for just this, but let me know if you prefer that and I can do it.
[Makefile-win32.txt](https://github.com/unwind/gimpilbm/files/389499/Makefile-win32.txt)

**Comment by unwind** [comment]
Hi!

Yeah, I kind of had those things you mentined with Windows in the back of
my mind when I did those changes. Good to hear it helped.

I see the warnings, and yes those should ideally be addressed. Not sure if
I got all of them, they can depend on the exact version of the libraries
that the plugin is built against and perhaps our systems don't match up.
Also some are in GTK/glib, and those are hard to address from the outside.

Regards,

/Emil

**Comment by midwan** [comment]
I also noticed one more thing, which was there on the previous versions also:
During operations when using the plugin, e.g. when loading or saving, there is a command prompt popping up in the background very quickly and then goes away.
My guess is that perhaps the plugin outputs text to the console, which on Windows means that it's thrown in a new window which closes down right after the message is displayed.

Could you please verify if this is correct?
If so, is it something we can disable? It seems a bit weird to have windows popping up and quickly disappearing when you're just loading an image... :)

**Comment by unwind** [comment]
Hi!

D'oh, that sounds annoying. I did a quick grep in the code last night and
it does contain a lot of printf()s, many of which should be conditional but
weren't in the default build. I changed that, but haven't tested. In fact I
don't know how to see stdout from a GIMP plugin in Linux, I'll try to find
out.

Regards,

/Emil

**Comment by unwind** [comment]
Hi again.

I did a quick test and it does seem it's quiet now. Please test.

Regards,

/Emil

**Comment by midwan** [comment]
Thanks for that, I will test tonight and report back with my results! :)

**Comment by midwan** [comment]
I've just tested, there is at least one are where it's still popping up a message in the console. That's during Export As, when the dialog about the save options comes up. I'm attaching a screenshot to demonstrate.
![gimp](https://cloud.githubusercontent.com/assets/3877365/17455458/6ab44fd6-5bb8-11e6-84ed-64225bad652a.png)

Meanwhile, there is a very quick open/close window event when opening a file also, but it's not a console window. It too quick to see what it is exactly, but the color is not black (like a console window). Must be some sort of message popping up and closing immediately, perhaps using GTK?

**Comment by unwind** [comment]
Hi!

I double-checked, and that string that ends in "running" is not present in
my binary (the .so on Linux) when built using DEBUGLEVEL=0 which is the
current default. Are you sure you had a properly rebuilt and up to date
binary installed when you got that? If I turn the DEBUGLEVEL back up to 2,
enabling VERBOSE in the code, I see the string in the binary again.

No idea about the other windows, of course a capture would be golden to see
what the window looks like and what it contains. I realize this is hard if
it's just there very briefly.

Regards,

/Emil

**Comment by midwan** [comment]
Hmm, I thought I did it with a "clean" first. To be sure, I'll do it again
tonight and see.

I don't know how to capture the other window yet, as it shows and hides so
far that you barely see it (but it is noticeable).
I'll see if I can come up with some idea to demonstrate this...

_Dimitris Panokostas_

**Comment by midwan** [comment]
I just tested it again. I had missed the -DDEBUGLEVEL=0 parameter in my Win32 makefile, which is why I was getting the message. 

However, with that option, I don't get the message but I do get an empty console window opening up (see attachment screenshot).

![gimp](https://cloud.githubusercontent.com/assets/3877365/17489640/587553a4-5d9f-11e6-999d-b0f017fa6d00.png)

**Comment by midwan** [comment]
@unwind 
I didn't notice this has been left open for so long... :)

I've just compiled the latest version without problems, I'll run a few tests and get back to you regarding the issue mentioned above.

Should we include the Windows Makefile in the project? If so, please keep this new one below, which includes the -DDEBUG... declaration:
[Makefile-win32.txt](https://github.com/unwind/gimpilbm/files/775008/Makefile-win32.txt)

**Comment by midwan** [comment]
Hmm, I get an error when trying to Save an image as IFF:
![image](https://cloud.githubusercontent.com/assets/3877365/22943552/3a271cae-f2ee-11e6-8e8f-ddbcf4ae5d31.png)

This happens after I select "Export As", select a filename and get the "Save as IFF" window to show up (which also pops up the black shell window in the background, still). Once I click on OK, using the default settings, this message comes up and no file is saved.

This was tested on GIMP 2.8.18

**Comment by unwind** [comment]
Hi!

Thanks for the Makefile, I'll add it.

Super strange about the save failing, please create a new Issue to track
this.

Regards,

/Emil
