### ISSUE TITLE
Save IFF function does not produce ILBM file

### ISSUE THREAD

**Issue by midwan** [unwind/gimpilbm#2]
I noticed that the saving functionality does not produce standard IFF-ILBM files (i.e. they cannot be opened anymore, not even by GIMP itself).

I checked the header of the resulting file and it may be the source of the problem there. The signature does not mention ILBMxxx but rather TILBMxx ?

**Comment by unwind** [comment]
Hi!

I've spent a while trying to understand this, but I can't reproduce that particular problem.

I did learn though that if you save an image created with the default settings in GIMP as ILBM, it won't load due to having 24 bits per pixel. Converting to indexed with max 32 colors seems to make it work.

Can you attach (in GIMP's .xcf format) an image that exports with the weird header?

**Comment by midwan** [comment]
Sorry for the big delay in getting back at this. :)
The problem can be recreated if you follow these steps:
- Load an IFF file with GIMP. I tried with an example of a 640x480 indexed color pic.
- Save the file as IFF with a new name. I used the default options in the IFF save dialog.
- Try to open the resulting file in GIMP or elsewhere. It is no longer seen as a valid IFF-ILBM file.

I'm attaching a file I used for testing, plus the resulting file after saving a copy. I hope it helps.

[snap.zip](https://github.com/unwind/gimpilbm/files/370009/snap.zip)

**Comment by unwind** [comment]
Closing this, pretty sure it's fixed in 0.9.11, would love feedback. Thanks for reporting and providing sample files, that was very helpful in getting this fixed.

**Comment by midwan** [comment]
Great!

I'll give it a try ASAP and get back to you.
I need to pick up my work for the Windows version anyway, so this is a
perfect excuse. :)

I had to modify the Makefile slightly to make it compile under Windows.
Therefore maybe it's best if we include both Makefiles (one for Linux, one
for windows environments) in the merged version?
Also, I found that I had to comment out one include in 3 files:

#include <netinet/in.h>

This was causing problems under a Windows compile for iff.h, ilbm.c,
ilbm.h. I'm not sure if it's needed for Linux, but the windows version
seems to work well even without it, this might need some further validation
though.

Finally, I have fixed a small typo in gui.c, line 53:

label = gtk_label_new("Alpha Treshold");

to the correct:
label = gtk_label_new("Alpha Threshold");

I'll probably do a fresh clone to validate that everything is up-to-date
and make any necessary changes before sending you a Pull Request (for real
this time). :)

Have a nice day!

_Dimitris Panokostas_

**Comment by unwind** [comment]
Sweet!

I have precious little time to spend on this, so don't be upset if handling
the PR takes long.

Regards,

/Emil

**Comment by midwan** [comment]
No worries mate, I fully understand. :)

BTW, do you know that you can cross-compile for Windows from within Linux?
http://wiki.gimp.org/index.php/Hacking:Building/Windows

I'll test that approach as well, if it requires less changes for the
Makefile for example it might be preferable.

_Dimitris Panokostas_

**Comment by unwind** [comment]
Nope, I haven't looked at cross-compiling this at all, I don't have access to Windows on my home machine(s).

I just pushed a commit (b6b770cc914bc218fa2544eb73236f3c37dbd596) that removes the dependency on the networking-related POSIX header, that was just silly. Hopefully that helps with porting.

**Comment by midwan** [comment]
Confirmed, it works as expected now. :+1:

**Comment by unwind** [comment]
Awesome, thanks!

With the limited testing I did, it's great to know it works for somebody
else than just me.

Thanks again for your interest and help!

Regards,

/Emil
