### ISSUE TITLE
Image does not display correctly

### ISSUE THREAD

**Issue by Sharalo** [unwind/gimpilbm#3]
Hi,
Most images from this archive appears only with their left part visible : http://www.t81t.net/IFF_BJH.zip
I use Gimp 2.8.18 under Windows and plugin v0.9.11 downloaded from http://blitterstudio.com/gimp-iff-plugin/

Regards

**Comment by unwind** [comment]
Hi!

Thanks! I really don't have enough tests or even test images for this.

That looks seriously broken, oops. I'll try to have a look, although my
bandwidth is small.

Regards,

/Emil

**Comment by unwind** [comment]
Okay, so it resisted a cursory read-through of the ILBM unpacking code ... And now the toddler is awake! :)

**Comment by midwan** [comment]
@Sharalo 
I could also do some tests here, and I still have my dev-environment to build the plugin for Windows so if we fix it, I can quickly compile a new version to test again.

@unwind 
It would be awesome if we could build the plugin from Visual Studio on Windows, and have it running on the debugger. Then issues like this would be fairly easy to pinpoint and fix. I'll spend some time to see how feasible that is...

**Comment by unwind** [comment]
I think this is fixed now, please see commit 8a755dc.

If you have any images that break this version, please file new issues!

Thanks for reporting this.
